Arquivo de configuração para o Nixpacks (sistema de build da Railway)
[phases.setup]

Instala o navegador Chromium, o Chromedriver e uma lista exaustiva de
dependências do sistema para maximizar a compatibilidade.
nixPkgs = [
"pkgs.chromium",
"pkgs.chromedriver",
"pkgs.stdenv.cc.cc.lib",
"pkgs.glib",
"pkgs.nss",
"pkgs.fontconfig",
"pkgs.freetype",
"pkgs.xorg.libX11",
"pkgs.xorg.libXcomposite",
"pkgs.xorg.libXcursor",
"pkgs.xorg.libXdamage",
"pkgs.xorg.libXext",
"pkgs.xorg.libXfixes",
"pkgs.xorg.libXi",
"pkgs.xorg.libXrandr",
"pkgs.xorg.libXrender",
"pkgs.xorg.libXtst",
"pkgs.cups",
"pkgs.dbus",
"pkgs.expat",
"pkgs.alsa-lib",
"pkgs.xorg.libxkbcommon",
"pkgs.at-spi2-atk",
"pkgs.pangox-compat",
# Adicionando mais bibliotecas gráficas como último recurso
"pkgs.gsettings-desktop-schemas",
"pkgs.gtk3",
"pkgs.libnotify",
"pkgs.pango"
]

[start]

Define o comando para iniciar a aplicação
command = "python roulette_monitor.py"
