name: Treinamento Diário do Modelo de IA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install pandas scikit-learn joblib psycopg2-binary

      - name: Rodar script de treinamento
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python train_model.py

      # --- PASSO MODIFICADO ---
      # O bloco 'run' anterior foi substituído por este.
      - name: Comitar e fazer push do novo modelo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Mensagem do commit
          commit_message: "[Auto] Atualiza modelo de IA treinado"
          
          # Especifica qual arquivo deve ser adicionado ao commit
          file_pattern: modelo_ia.pkl
