name: Treinamento Diário do Modelo de IA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install pandas scikit-learn joblib psycopg2-binary

      - name: Rodar script de treinamento
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python train_model.py

      - name: Comitar e fazer push do novo modelo
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add modelo_ia.pkl
          # Verifica se há algo para comitar
          if ! (git diff --quiet && git diff --staged --quiet); then
            git commit -m "[Auto] Atualiza modelo de IA treinado"
            # A linha abaixo faz o push usando um token de autenticação explícito
            git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref_name }}
          else
            echo "Nenhuma mudança no modelo para comitar."
          fi
